// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

// Non-generic base overloads for functions that are ALSO generated by CsWin32.
// The CsWin32-generated P/Invoke externs serve as non-generic bases that break
// the IHandle<HWND> recursion in generic wrappers. These stubs are only needed
// for functions that have NO CsWin32 generation and NO dedicated PInvoke.*.cs fix.
//
// Functions fixed via direct-return in their PInvoke.*.cs files:
//   GetSystemMenu, DrawMenuBar, GetMenu, SetMenu, EndDialog, GetDlgItem,
//   HtmlHelp, ImmReleaseContext, RegisterDragDrop, SetScrollPos

namespace Windows.Win32;

internal static partial class PInvoke
{
    // All previously-stubbed functions have been moved to their respective
    // PInvoke.*.cs files with direct returns in the generic body, or are
    // covered by CsWin32-generated non-generic P/Invoke externs.
}
